language: node_js
node_js:
  - "stable"
case:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
depeloy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: test-ci